// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtrq8-B6nrIPJRYvO4XNzHqAuRPI4IUNk',
    appId: '1:215844579757:web:549446953de027c669d924',
    messagingSenderId: '215844579757',
    projectId: 'marsilino-a7023',
    authDomain: 'marsilino-a7023.firebaseapp.com',
    storageBucket: 'marsilino-a7023.firebasestorage.app',
    measurementId: 'G-M409G09RK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP9v23GmhSiq4Ta604Og6Msc1IygXweFM',
    appId: '1:215844579757:android:b2d8f7ff9d9d865e69d924',
    messagingSenderId: '215844579757',
    projectId: 'marsilino-a7023',
    storageBucket: 'marsilino-a7023.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC3FoGVTmknNaAzoOrb5pJaHXPdkytWpk',
    appId: '1:215844579757:ios:fc8786e48445050469d924',
    messagingSenderId: '215844579757',
    projectId: 'marsilino-a7023',
    storageBucket: 'marsilino-a7023.firebasestorage.app',
    iosBundleId: 'com.example.restaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC3FoGVTmknNaAzoOrb5pJaHXPdkytWpk',
    appId: '1:215844579757:ios:fc8786e48445050469d924',
    messagingSenderId: '215844579757',
    projectId: 'marsilino-a7023',
    storageBucket: 'marsilino-a7023.firebasestorage.app',
    iosBundleId: 'com.example.restaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtrq8-B6nrIPJRYvO4XNzHqAuRPI4IUNk',
    appId: '1:215844579757:web:ab4bdf2e6ff5988069d924',
    messagingSenderId: '215844579757',
    projectId: 'marsilino-a7023',
    authDomain: 'marsilino-a7023.firebaseapp.com',
    storageBucket: 'marsilino-a7023.firebasestorage.app',
    measurementId: 'G-NEMVC6M8GE',
  );
}
